name: Update README with Contributors

on:
  push:
    branches:
      - main  # Change this if your default branch is different

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyGithub

    - name: Update README.md
      env:
        INPUT_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # or your personal access token
        INPUT_REPO_NAME: ${{ github.repository }}
      run: python update_readme.py

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git commit -m "Update contributors list in README"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
